<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <!-- ========================== Properties ========================== -->
  <xacro:property name="wheel_d" value="0.072" />
  <xacro:property name="wheel_r" value="${wheel_d/2.0}" /> <!-- back wheel radius -->
  <xacro:property name="wheel_w" value="0.008" /> <!-- wheel width -->
  <xacro:property name="base_radius" value="0.175" />
  <xacro:property name="base_thickness" value="0.02" />
  <xacro:property name="base_z_offset" value="0.05" />
  <xacro:property name="head_x" value="0.03" />
  <xacro:property name="head_y" value="0.02" />
  <xacro:property name="head_z" value="0.02" />
  <xacro:property name="front_wheel_r" value="${(wheel_r - base_thickness/2) / 2}" />
  <xacro:property name="passive_holder_len" value="0.0006" />
  <xacro:property name="passive_wheel_r" value="0.02" />
  <xacro:property name="passive_wheel_w" value="0.01" />

  <material name="wheel_black">
    <color rgba="0.05 0.05 0.05 1.0" />
  </material>


  <!-- ========================== Links ========================== -->
  <link name="base_footprint" /> <!-- dummy link -->

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_thickness}" />
      </geometry>
      <material name="base_red">
        <color rgba="0.8 0.2 0.2 1.0" />
      </material>
    </visual>
    <inertial>
      <mass value="5.0" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>

  <link name="head_link">
    <visual>
      <geometry>
        <box size="${head_x} ${head_y} ${head_z}" />
      </geometry>
      <material name="head_blue">
        <color rgba="0.15 0.4 0.9 1.0" />
      </material>
    </visual>
  </link>

  <!-- Back wheels (cylinders) -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_w}" />
      </geometry>
      <material name="wheel_black" />
    </visual>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_r}" length="${wheel_w}" />
      </geometry>
      <material name="wheel_black" />
    </visual>
  </link>

  <!-- Rotation markers -->
<link name="left_wheel_marker">
  <visual>
    <geometry>
      <!-- Thin rectangle along the wheel axis -->
      <box size="${wheel_r*0.2} ${wheel_w * 0.1} ${wheel_r*1.2}" />
    </geometry>
    <material name="marker_white">
      <color rgba="1 1 1 1"/>
    </material>
  </visual>
</link>

  <link name="right_wheel_marker">
    <visual>
      <geometry>
        <box size="${wheel_r*1.2} ${wheel_w*0.1} ${wheel_r*0.08}" />
      </geometry>
      <material name="marker_white">
        <color rgba="1 1 1 1" />
      </material>
    </visual>
  </link>

  <link name="passive_wheel_holder">
    <visual>
      <geometry>
        <cylinder radius="${passive_wheel_r}" length="${passive_holder_len}" />
      </geometry>
      <material name="white">
        <color rgba="0.95 0.95 0.95 1.0" />
      </material>
    </visual>
  </link>


  <!-- Passive wheel as sphere -->
  <link name="passive_wheel">
    <visual>
      <geometry>
        <sphere radius="${passive_wheel_r}" />
      </geometry>
      <material name="white" />
    </visual>
  </link>

  <!-- ========================== Joints ========================== -->
  <joint name="footprint_to_base" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${base_z_offset}" rpy="0 0 0" />
  </joint>

  <joint name="base_to_head" type="fixed">
    <parent link="base_link" />
    <child link="head_link" />
    <origin xyz="${base_radius - 0.02} 0 ${base_thickness/2.0 + head_z/2.0}" rpy="0 0 0" />
  </joint>


  <joint name="base_to_left_wheel" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel" />
    <origin xyz="${-wheel_w/2} ${base_radius + 0.001} 0" rpy="${pi/2} ${pi/2} 0" />
    <axis xyz="1 0 0" />
  </joint>


  <joint name="left_wheel_marker_fixed" type="fixed">
  <parent link="left_wheel"/>
  <child link="left_wheel_marker"/>
  <origin xyz="0 0 ${-wheel_w / 2}" rpy="${pi/2} 0 ${pi/2}"/>
</joint>

  <joint name="base_to_right_wheel" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel" />
    <origin xyz="${-wheel_w/2} ${-base_radius} 0" rpy="${pi/2} ${pi/2} 0" />
    <axis xyz="1 0 0" />
  </joint>

  <joint name="right_wheel_marker_fixed" type="fixed">
    <parent link="right_wheel" />
    <child link="right_wheel_marker" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <joint name="base_to_passive_holder" type="fixed">
    <parent link="base_link" />
    <child link="passive_wheel_holder" />
    <origin xyz="${base_radius - 0.02} 0 ${-base_thickness/2.0}" rpy="0 0 0" />
  </joint>

  <joint name="holder_to_passive_wheel" type="continuous">
    <parent link="passive_wheel_holder" />
    <child link="passive_wheel" />
    <origin xyz="0 0 ${-passive_wheel_r}" rpy="0 0 0" />
    <axis xyz="0 0 1" />
  </joint>

</robot>